# Generated by Django 3.2.7 on 2021-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_remove_departamento_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad_reguladora',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ent_reg/'),
        ),
        migrations.AddField(
            model_name='ong',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ong/'),
        ),
    ]
