# Generated by Django 3.2.7 on 2021-11-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0002_fauna_poblacion_flora_poblacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zona_protegida',
            old_name='coordenada_x',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='zona_protegida',
            old_name='coordenada_y',
            new_name='longitud',
        ),
    ]
