# Generated by Django 3.2.7 on 2021-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0003_auto_20211104_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_protegida',
            name='caracteristicas',
            field=models.CharField(default=0.0005693069306930693, max_length=2000),
            preserve_default=False,
        ),
    ]
