# Generated by Django 3.2.7 on 2021-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0004_zona_protegida_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_protegida',
            name='caracteristicas',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='zona_protegida',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
    ]
