# Generated by Django 3.2.7 on 2021-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0005_auto_20211104_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_protegida',
            name='image_url',
            field=models.CharField(default=0.000179928928073411, max_length=60),
            preserve_default=False,
        ),
    ]
