# Generated by Django 3.2.7 on 2021-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0007_alter_zona_protegida_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_protegida',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
