# Generated by Django 3.2.7 on 2021-11-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0008_alter_zona_protegida_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fauna_zona',
            name='observaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flora_zona',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
