# Generated by Django 3.2.7 on 2021-11-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0009_auto_20211104_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona_protegida',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
