# Generated by Django 3.2.7 on 2021-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0010_zona_protegida_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona_protegida',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
