# Generated by Django 3.2.7 on 2021-11-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0011_alter_zona_protegida_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flora_zona',
            name='fauna',
        ),
        migrations.AddField(
            model_name='flora_zona',
            name='flora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zonas.flora'),
        ),
    ]
