# Generated by Django 3.2.7 on 2021-11-09 22:12

from django.db import migrations, models
import zonas.models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0014_auto_20211109_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fauna',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=zonas.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='flora',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=zonas.models.image_upload_handler),
        ),
        migrations.AlterField(
            model_name='zona_protegida',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=zonas.models.image_upload_handler),
        ),
    ]
