# Generated by Django 3.2.7 on 2021-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0016_alter_zona_protegida_geojson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fauna',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flora',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
