# Generated by Django 3.2.7 on 2021-11-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0017_auto_20211119_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fauna_zona',
            name='poblacion',
        ),
        migrations.RemoveField(
            model_name='flora_zona',
            name='poblacion',
        ),
    ]
