# Generated by Django 3.2.7 on 2021-11-19 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0005_auto_20211119_1240'),
        ('zonas', '0018_auto_20211119_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.zona_protegida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fauna_poblacion',
            name='fauna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.fauna_zona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fauna_zona',
            name='fauna',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.fauna'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fauna_zona',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.zona_protegida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flora_poblacion',
            name='flora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.flora_zona'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flora_zona',
            name='flora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.flora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flora_zona',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zonas.zona_protegida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zona_protegida',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='municipios.municipio'),
            preserve_default=False,
        ),
    ]
